# Generated by Django 5.0.1 on 2024-01-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_book_author_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
